spring:
  datasource:
    # MySQL 기본 설정
    url: jdbc:mysql://localhost:3306/rolling_db?useUnicode=true&characterEncoding=euckr
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gkdms~!1357
  jpa:
    database: mysql # MySQL 상세 지정
    show-sql: true # API 호출 시 sql문을 출력
    properties:
      hibernate:
        format_sql: true
        ddl-auto: nones
    defer-datasource-initialization: true
  security:
    user:
      name: user
      password: 1111
    oauth2:
      client:
        registration:
          google:
            client-id: 23578035506-nn4r60idvkau3gt6o346u6isr044f1eg.apps.googleusercontent.com
            client-secret: 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
            scope:
#  sql:
#    init:
#      mode: always

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

logging:
  level:
    org:
      springframework: debug
      springframework.web: debug