INSERT INTO paper (paper_no, paper_maker, paper_receiver) VALUES (1, '1', 'a')
INSERT INTO paper (paper_no, paper_maker, paper_receiver) VALUES (2, '2', 'a')
INSERT INTO paper (paper_no, paper_maker, paper_receiver) VALUES (3, '3', 'a')

INSERT INTO rolling_paper (rollingpaper_id, rollingpaper_title, rollingpaper_sent_from) VALUES (1, 'a', '2-1반')
INSERT INTO rolling_paper (rollingpaper_id, rollingpaper_title, rollingpaper_sent_from) VALUES (2, 'b', '2-2반')
INSERT INTO rolling_paper (rollingpaper_id, rollingpaper_title, rollingpaper_sent_from) VALUES (3, 'c', '2-3반')
INSERT INTO rolling_paper (rollingpaper_id, rollingpaper_title, rollingpaper_sent_from) VALUES (4, 'd', '2-4반')
INSERT INTO rolling_paper (rollingpaper_id, rollingpaper_title, rollingpaper_sent_from) VALUES (5, 'e', '2-5반')
INSERT INTO rolling_paper (rollingpaper_id, rollingpaper_title, rollingpaper_sent_from) VALUES (6, 'f', '2-6반')