INSERT INTO rollingpaper (maker, receiver, submit_date, title) VALUES ('김길동', '1-1반', now(), '우리의 졸업을 축하합니다.')
INSERT INTO rollingpaper (maker, receiver, submit_date, title) VALUES ('김길동', '1-1반', now(), '우리의 졸업을 축하합니다.')
INSERT INTO rollingpaper (maker, receiver, submit_date, title) VALUES ('김길동', '1-1반', now(), '우리의 졸업을 축하합니다.')
INSERT INTO rollingpaper (maker, receiver, submit_date, title) VALUES ('김길동', '1-1반', now(), '우리의 졸업을 축하합니다.')
INSERT INTO paper (content, writer) VALUES ('content1', 'writer1')
